version: "3"
services:
  server:
    build: python
    restart: always
    ports:
      - "5000:5000"
    links:
      - db
    networks:
      - my-network
  db:
    image: 'postgres:15.4-alpine3.18'
    container_name: db
    environment:
      - DB_NAME=fruits
      - PGDATA=/var/lib/postgresql/data/fruits
      - POSTGRES_PASSWORD=123456
    ports:
      - '5431:5432'
    restart: always
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d:ro
    networks:
      - my-network

networks:
  my-network: